# Generated by Django 2.0.7 on 2020-10-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
