# Generated by Django 2.0.7 on 2020-10-01 10:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0002_auto_20201001_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=25, null=True, region=None, verbose_name='phone number'),
        ),
    ]
