# Generated by Django 2.2.15 on 2020-10-06 09:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0005_auto_20201006_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=17, null=True, region=None, verbose_name='phone number'),
        ),
    ]
