# Generated by Django 2.2.15 on 2020-10-19 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0008_auto_20201017_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_book',
            name='img',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='book-post-images', region_name='us-east-2'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='post_book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
