# Generated by Django 2.2.15 on 2020-10-21 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0009_auto_20201019_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_book',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
