# Generated by Django 2.2.15 on 2020-10-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuser', '0011_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
